defaults:
  - cost: default_cost_config
  - motion_primitives: default_motion_primitives_config
  - planner: hybrid_a_star
  - controller: mpc
  - vehicle: renault_twizy
  - noise: no_noise
  - scenario: overtake_scenario
  - runtime: default_runtime_config
